name: TestDriver.ai

on:
  push:
    branches: ["main", "windows-testdriver"]
  pull_request:
  workflow_dispatch:

jobs:
  start_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1. Run your application container
      - name: Start Nginx Container
        run: docker run -d -p 8080:80 nginx:latest

      # 2. Run ngrok in a Docker container, tunneling port 8080
      - name: Start ngrok Container
        run: |
          docker run -d --name myngrok \
            -e NGROK_AUTHTOKEN=${{ secrets.NGROK_AUTH_TOKEN }} \
            -p 4040:4040 \
            ngrok/ngrok:latest http host.docker.internal:8080

      # Give ngrok a moment to establish the tunnel
      - name: Wait for ngrok
        run: sleep 5

      # 3. Extract the public URL from ngrok logs
      - name: Get ngrok URL
        id: geturl
        run: |
          # Fetch logs from the ngrok container
          logs=$(docker logs myngrok 2>&1)
          echo "$logs"
          APP_URL=$(echo "$logs" | grep -oE "https://[0-9a-zA-Z.-]+\.ngrok-free.app")
          echo "Found URL: $APP_URL"
          echo "app_url=$APP_URL" >> $GITHUB_OUTPUT
      - name: Debug ngrok logs
        run: cat ngrok.log

      # 4. Test against the public URL in the same job
      - name: Test URL
        run: |
          echo "Testing $APP_URL"
          curl "$APP_URL"
