name: TestDriver.ai

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: "TestDriver"
    runs-on: ubuntu-latest
    steps:
      - uses: testdriverai/action@main
        with:
          key: ${{secrets.TESTDRIVER_API_KEY}}
          prompt: |
            1. /run testdriver/test.yml
          prerun: |
            npm install
            npm install dashcam-chrome
            node scripts/generate-env.mjs
            if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
            npm run build -- --filter='!@mainframe-api/docs' --ui=stream --output-logs=errors-only
            npm run db:migrate
            $logPath = ".\logs.txt"
            Start-Job -ScriptBlock {
              npx turbo run "@mainframe-api/node#serve" dev --env-mode=loose --filter='!@mainframe-api/node' --filter='!@mainframe-api/docs' --ui=tui
            } >> $logPath
            # Wait for the port to be live by monitoring the output logs
            $portLive = $false

            while (-not $portLive) {
                Start-Sleep -Seconds 1
                if (Select-String -Path $logPath -Pattern "Local:   http://localhost:8744/") {
                    $portLive = $true
                }
            }
            Start-Process "C:/Program Files/Google/Chrome/Application/chrome.exe" -ArgumentList "--start-maximized", "--load-extension=$(pwd)/node_modules/dashcam-chrome/build", "${{ env.LOCALHOST }}"
            exit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FORCE_COLOR: "3"
          LOCALHOST: "http://localhost:8744"
