name: TestDriver.ai

on:
  push:
    branches: ["main", "windows-testdriver"]
  pull_request:
  workflow_dispatch:

jobs:
  start_container:
    runs-on: ubuntu-latest
    outputs:
      app_url: ${{ steps.expose.outputs.app_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Run Nginx Container
        run: |
          docker run -d -p 8080:80 nginx:latest
      
      - name: Install ngrok
        run: |
          wget https://bin.equinox.io/c/111111/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64.zip
          sudo mv ngrok /usr/local/bin
      
      - name: Start ngrok and expose
        id: expose
        run: |
          ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }} || { echo "Ngrok auth token failed"; exit 1; }
          ngrok http http://localhost:8080 > ngrok.log &
          sleep 10
          curl --silent http://localhost:4040/api/tunnels > tunnels.json || { echo "Failed to fetch tunnels"; exit 1; }
          APP_URL=$(jq -r '.tunnels[0].public_url' tunnels.json)
          echo "Generated URL: $APP_URL"
          echo "app_url=$APP_URL" >> $GITHUB_OUTPUT
          curl $APP_URL/health-check || { echo "Health check failed"; exit 1; }
